name: 'Packages Split'

on:
    push:
        branches:
            - main
        tags:
            - '*'

env:
    # 1. for Github split
    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}


jobs:
    packages_split:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                # define package to repository map
                package:
                    -
                        local_path: 'survey'
                        split_repository: 'katana-survey'

        steps:
            -   uses: actions/checkout@v2
            # with tag
            -
                if: "startsWith(github.ref, 'refs/tags/')"
                uses: danharrin/monorepo-split-github-action@v2.4.0
                with:
                    tag: ${GITHUB_REF#refs/tags/}

                    # ↓ split "packages/survey" directory
                    package_directory: 'packages/${{ matrix.package.local_path }}'

                    # ↓ into https://github.com/katanadha/survey repository
                    repository_organization: 'katanadha'
                    repository_name: '${{ matrix.package.split_repository }}'

                    # [optional, with "github.com" as default]
                    repository_host: git.private.com:1234

                    # ↓ the user signed under the split commit
                    user_name: "kaizen-ci"
                    user_email: "info@kaizen-ci.org"